//! libvpx v1.17.0 encoder API (vpx_encoder.h + vp8cx.h), generated by bindgen 0.73 — when scripts/build-libvpx.* pin
//! another version, regenerate from its headers (vendor/libvpx/<target>/include):
//!   bindgen ffi.h --no-layout-tests --no-doc-comments --use-core \
//!     --allowlist-function 'vpx_codec_(enc_init_ver|enc_config_default|enc_config_set|encode|get_cx_data|destroy|control_|error|error_detail|vp9_cx)|vpx_img_wrap' \
//!     --allowlist-var 'VPX_.*|VP8E_.*|VP9E_.*|VP8_EFLAG_FORCE_KF' --allowlist-type 'vpx_.*|vp8e_.*|vp9e_.*' -- -I<include>
//! (ffi.h: `#include <vpx/vpx_encoder.h>` and `<vpx/vp8cx.h>`). `c_ulong`/`c_long` follow the target (32-bit on
//! Windows) and enums are 32-bit everywhere, so this one file serves every OS.
#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case, dead_code, clippy::all)]

/* automatically generated by rust-bindgen 0.73.2 */

pub const VPX_IMAGE_ABI_VERSION: u32 = 5;
pub const VPX_IMG_FMT_PLANAR: u32 = 256;
pub const VPX_IMG_FMT_UV_FLIP: u32 = 512;
pub const VPX_IMG_FMT_HAS_ALPHA: u32 = 1024;
pub const VPX_IMG_FMT_HIGHBITDEPTH: u32 = 2048;
pub const VPX_PLANE_PACKED: u32 = 0;
pub const VPX_PLANE_Y: u32 = 0;
pub const VPX_PLANE_U: u32 = 1;
pub const VPX_PLANE_V: u32 = 2;
pub const VPX_PLANE_ALPHA: u32 = 3;
pub const VPX_CODEC_ABI_VERSION: u32 = 9;
pub const VPX_CODEC_CAP_DECODER: u32 = 1;
pub const VPX_CODEC_CAP_ENCODER: u32 = 2;
pub const VPX_CODEC_CAP_HIGHBITDEPTH: u32 = 4;
pub const VPX_TPL_ABI_VERSION: u32 = 5;
pub const VPX_EXT_RATECTRL_ABI_VERSION: u32 = 12;
pub const VPX_RC_MAX_STATIC_GF_GROUP_LENGTH: u32 = 250;
pub const VPX_RC_MAX_REF_FRAMES: u32 = 4;
pub const VPX_DEFAULT_Q: i32 = -1;
pub const VPX_DEFAULT_RDMULT: i32 = -1;
pub const VPX_TS_MAX_PERIODICITY: u32 = 16;
pub const VPX_TS_MAX_LAYERS: u32 = 5;
pub const VPX_MAX_LAYERS: u32 = 12;
pub const VPX_SS_MAX_LAYERS: u32 = 5;
pub const VPX_SS_DEFAULT_LAYERS: u32 = 1;
pub const VPX_ENCODER_ABI_VERSION: u32 = 39;
pub const VPX_CODEC_CAP_PSNR: u32 = 65536;
pub const VPX_CODEC_CAP_OUTPUT_PARTITION: u32 = 131072;
pub const VPX_CODEC_USE_PSNR: u32 = 65536;
pub const VPX_CODEC_USE_OUTPUT_PARTITION: u32 = 131072;
pub const VPX_CODEC_USE_HIGHBITDEPTH: u32 = 262144;
pub const VPX_FRAME_IS_KEY: u32 = 1;
pub const VPX_FRAME_IS_DROPPABLE: u32 = 2;
pub const VPX_FRAME_IS_INVISIBLE: u32 = 4;
pub const VPX_FRAME_IS_FRAGMENT: u32 = 8;
pub const VPX_ERROR_RESILIENT_DEFAULT: u32 = 1;
pub const VPX_ERROR_RESILIENT_PARTITIONS: u32 = 2;
pub const VPX_EFLAG_FORCE_KF: u32 = 1;
pub const VPX_EFLAG_CALCULATE_PSNR: u32 = 2;
pub const VPX_DL_REALTIME: u32 = 1;
pub const VPX_DL_GOOD_QUALITY: u32 = 1000000;
pub const VPX_DL_BEST_QUALITY: u32 = 0;
pub const vpx_img_fmt_VPX_IMG_FMT_NONE: vpx_img_fmt = 0;
pub const vpx_img_fmt_VPX_IMG_FMT_YV12: vpx_img_fmt = 769;
pub const vpx_img_fmt_VPX_IMG_FMT_I420: vpx_img_fmt = 258;
pub const vpx_img_fmt_VPX_IMG_FMT_I422: vpx_img_fmt = 261;
pub const vpx_img_fmt_VPX_IMG_FMT_I444: vpx_img_fmt = 262;
pub const vpx_img_fmt_VPX_IMG_FMT_I440: vpx_img_fmt = 263;
pub const vpx_img_fmt_VPX_IMG_FMT_NV12: vpx_img_fmt = 265;
pub const vpx_img_fmt_VPX_IMG_FMT_I42016: vpx_img_fmt = 2306;
pub const vpx_img_fmt_VPX_IMG_FMT_I42216: vpx_img_fmt = 2309;
pub const vpx_img_fmt_VPX_IMG_FMT_I44416: vpx_img_fmt = 2310;
pub const vpx_img_fmt_VPX_IMG_FMT_I44016: vpx_img_fmt = 2311;
pub type vpx_img_fmt = ::core::ffi::c_uint;
pub use self::vpx_img_fmt as vpx_img_fmt_t;
pub const vpx_color_space_VPX_CS_UNKNOWN: vpx_color_space = 0;
pub const vpx_color_space_VPX_CS_BT_601: vpx_color_space = 1;
pub const vpx_color_space_VPX_CS_BT_709: vpx_color_space = 2;
pub const vpx_color_space_VPX_CS_SMPTE_170: vpx_color_space = 3;
pub const vpx_color_space_VPX_CS_SMPTE_240: vpx_color_space = 4;
pub const vpx_color_space_VPX_CS_BT_2020: vpx_color_space = 5;
pub const vpx_color_space_VPX_CS_RESERVED: vpx_color_space = 6;
pub const vpx_color_space_VPX_CS_SRGB: vpx_color_space = 7;
pub type vpx_color_space = ::core::ffi::c_uint;
pub use self::vpx_color_space as vpx_color_space_t;
pub const vpx_color_range_VPX_CR_STUDIO_RANGE: vpx_color_range = 0;
pub const vpx_color_range_VPX_CR_FULL_RANGE: vpx_color_range = 1;
pub type vpx_color_range = ::core::ffi::c_uint;
pub use self::vpx_color_range as vpx_color_range_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_image {
    pub fmt: vpx_img_fmt_t,
    pub cs: vpx_color_space_t,
    pub range: vpx_color_range_t,
    pub w: ::core::ffi::c_uint,
    pub h: ::core::ffi::c_uint,
    pub bit_depth: ::core::ffi::c_uint,
    pub d_w: ::core::ffi::c_uint,
    pub d_h: ::core::ffi::c_uint,
    pub r_w: ::core::ffi::c_uint,
    pub r_h: ::core::ffi::c_uint,
    pub x_chroma_shift: ::core::ffi::c_uint,
    pub y_chroma_shift: ::core::ffi::c_uint,
    pub planes: [*mut ::core::ffi::c_uchar; 4usize],
    pub stride: [::core::ffi::c_int; 4usize],
    pub bps: ::core::ffi::c_int,
    pub user_priv: *mut ::core::ffi::c_void,
    pub img_data: *mut ::core::ffi::c_uchar,
    pub img_data_owner: ::core::ffi::c_int,
    pub self_allocd: ::core::ffi::c_int,
    pub fb_priv: *mut ::core::ffi::c_void,
}
pub type vpx_image_t = vpx_image;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_image_rect {
    pub x: ::core::ffi::c_uint,
    pub y: ::core::ffi::c_uint,
    pub w: ::core::ffi::c_uint,
    pub h: ::core::ffi::c_uint,
}
pub type vpx_image_rect_t = vpx_image_rect;
unsafe extern "C" {
    pub fn vpx_img_wrap(
        img: *mut vpx_image_t,
        fmt: vpx_img_fmt_t,
        d_w: ::core::ffi::c_uint,
        d_h: ::core::ffi::c_uint,
        stride_align: ::core::ffi::c_uint,
        img_data: *mut ::core::ffi::c_uchar,
    ) -> *mut vpx_image_t;
}
pub const vpx_codec_err_t_VPX_CODEC_OK: vpx_codec_err_t = 0;
pub const vpx_codec_err_t_VPX_CODEC_ERROR: vpx_codec_err_t = 1;
pub const vpx_codec_err_t_VPX_CODEC_MEM_ERROR: vpx_codec_err_t = 2;
pub const vpx_codec_err_t_VPX_CODEC_ABI_MISMATCH: vpx_codec_err_t = 3;
pub const vpx_codec_err_t_VPX_CODEC_INCAPABLE: vpx_codec_err_t = 4;
pub const vpx_codec_err_t_VPX_CODEC_UNSUP_BITSTREAM: vpx_codec_err_t = 5;
pub const vpx_codec_err_t_VPX_CODEC_UNSUP_FEATURE: vpx_codec_err_t = 6;
pub const vpx_codec_err_t_VPX_CODEC_CORRUPT_FRAME: vpx_codec_err_t = 7;
pub const vpx_codec_err_t_VPX_CODEC_INVALID_PARAM: vpx_codec_err_t = 8;
pub const vpx_codec_err_t_VPX_CODEC_LIST_END: vpx_codec_err_t = 9;
pub type vpx_codec_err_t = ::core::ffi::c_uint;
pub type vpx_codec_caps_t = ::core::ffi::c_long;
pub type vpx_codec_flags_t = ::core::ffi::c_long;
#[repr(C)]
#[derive(Debug)]
pub struct vpx_codec_iface {
    _unused: [u8; 0],
}
pub type vpx_codec_iface_t = vpx_codec_iface;
#[repr(C)]
#[derive(Debug)]
pub struct vpx_codec_priv {
    _unused: [u8; 0],
}
pub type vpx_codec_priv_t = vpx_codec_priv;
pub type vpx_codec_iter_t = *const ::core::ffi::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct vpx_codec_ctx {
    pub name: *const ::core::ffi::c_char,
    pub iface: *const vpx_codec_iface,
    pub err: vpx_codec_err_t,
    pub err_detail: *const ::core::ffi::c_char,
    pub init_flags: vpx_codec_flags_t,
    pub config: vpx_codec_ctx__bindgen_ty_1,
    pub priv_: *mut vpx_codec_priv_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union vpx_codec_ctx__bindgen_ty_1 {
    pub dec: *mut vpx_codec_dec_cfg,
    pub enc: *const vpx_codec_enc_cfg,
    pub raw: *const ::core::ffi::c_void,
}
pub type vpx_codec_ctx_t = vpx_codec_ctx;
pub const vpx_bit_depth_VPX_BITS_8: vpx_bit_depth = 8;
pub const vpx_bit_depth_VPX_BITS_10: vpx_bit_depth = 10;
pub const vpx_bit_depth_VPX_BITS_12: vpx_bit_depth = 12;
pub type vpx_bit_depth = ::core::ffi::c_uint;
pub use self::vpx_bit_depth as vpx_bit_depth_t;
unsafe extern "C" {
    pub fn vpx_codec_error(ctx: *const vpx_codec_ctx_t) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn vpx_codec_error_detail(ctx: *const vpx_codec_ctx_t) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn vpx_codec_destroy(ctx: *mut vpx_codec_ctx_t) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_control_(
        ctx: *mut vpx_codec_ctx_t,
        ctrl_id: ::core::ffi::c_int,
        ...
    ) -> vpx_codec_err_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VpxTplBlockStats {
    pub row: i16,
    pub col: i16,
    pub intra_cost: i64,
    pub inter_cost: i64,
    pub mv_r: i16,
    pub mv_c: i16,
    pub srcrf_rate: i64,
    pub srcrf_dist: i64,
    pub pred_error: i64,
    pub inter_pred_err: i64,
    pub intra_pred_err: i64,
    pub ref_frame_index: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VpxTplFrameStats {
    pub frame_width: ::core::ffi::c_int,
    pub frame_height: ::core::ffi::c_int,
    pub num_blocks: ::core::ffi::c_int,
    pub block_stats_list: *mut VpxTplBlockStats,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VpxTplGopStats {
    pub size: ::core::ffi::c_int,
    pub frame_stats_list: *mut VpxTplFrameStats,
}
pub const vpx_rc_type_VPX_RC_NONE: vpx_rc_type = 0;
pub const vpx_rc_type_VPX_RC_QP: vpx_rc_type = 1;
pub const vpx_rc_type_VPX_RC_GOP: vpx_rc_type = 2;
pub const vpx_rc_type_VPX_RC_RDMULT: vpx_rc_type = 4;
pub const vpx_rc_type_VPX_RC_GOP_QP: vpx_rc_type = 3;
pub const vpx_rc_type_VPX_RC_GOP_QP_RDMULT: vpx_rc_type = 7;
pub type vpx_rc_type = ::core::ffi::c_uint;
pub use self::vpx_rc_type as vpx_rc_type_t;
pub const vpx_ext_rc_mode_VPX_RC_QMODE: vpx_ext_rc_mode = 0;
pub const vpx_ext_rc_mode_VPX_RC_VBR: vpx_ext_rc_mode = 1;
pub const vpx_ext_rc_mode_VPX_RC_CQ: vpx_ext_rc_mode = 2;
pub type vpx_ext_rc_mode = ::core::ffi::c_uint;
pub use self::vpx_ext_rc_mode as vpx_ext_rc_mode_t;
pub const vpx_rc_frame_update_type_VPX_RC_INVALID_UPDATE_TYPE: vpx_rc_frame_update_type = -1;
pub const vpx_rc_frame_update_type_VPX_RC_KF_UPDATE: vpx_rc_frame_update_type = 0;
pub const vpx_rc_frame_update_type_VPX_RC_LF_UPDATE: vpx_rc_frame_update_type = 1;
pub const vpx_rc_frame_update_type_VPX_RC_GF_UPDATE: vpx_rc_frame_update_type = 2;
pub const vpx_rc_frame_update_type_VPX_RC_ARF_UPDATE: vpx_rc_frame_update_type = 3;
pub const vpx_rc_frame_update_type_VPX_RC_OVERLAY_UPDATE: vpx_rc_frame_update_type = 4;
pub const vpx_rc_frame_update_type_VPX_RC_MID_OVERLAY_UPDATE: vpx_rc_frame_update_type = 5;
pub const vpx_rc_frame_update_type_VPX_RC_USE_BUF_FRAME: vpx_rc_frame_update_type = 6;
pub type vpx_rc_frame_update_type = ::core::ffi::c_int;
pub use self::vpx_rc_frame_update_type as vpx_rc_frame_update_type_t;
pub const vpx_rc_ref_name_VPX_RC_INVALID_REF_FRAME: vpx_rc_ref_name = -1;
pub const vpx_rc_ref_name_VPX_RC_INTRA_FRAME: vpx_rc_ref_name = 0;
pub const vpx_rc_ref_name_VPX_RC_LAST_FRAME: vpx_rc_ref_name = 1;
pub const vpx_rc_ref_name_VPX_RC_GOLDEN_FRAME: vpx_rc_ref_name = 2;
pub const vpx_rc_ref_name_VPX_RC_ALTREF_FRAME: vpx_rc_ref_name = 3;
pub type vpx_rc_ref_name = ::core::ffi::c_int;
pub use self::vpx_rc_ref_name as vpx_rc_ref_name_t;
pub type vpx_rc_model_t = *mut ::core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sb_parameters {
    pub q_index: ::core::ffi::c_int,
    pub rdmult: ::core::ffi::c_int,
}
pub type sb_params = sb_parameters;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_encodeframe_decision {
    pub q_index: ::core::ffi::c_int,
    pub rdmult: ::core::ffi::c_int,
    pub delta_q_uv: ::core::ffi::c_int,
    pub sb_params_list: *mut sb_params,
}
pub type vpx_rc_encodeframe_decision_t = vpx_rc_encodeframe_decision;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_encodeframe_info {
    pub frame_type: ::core::ffi::c_int,
    pub show_index: ::core::ffi::c_int,
    pub coding_index: ::core::ffi::c_int,
    pub gop_index: ::core::ffi::c_int,
    pub ref_frame_coding_indexes: [::core::ffi::c_int; 3usize],
    pub ref_frame_valid_list: [::core::ffi::c_int; 3usize],
    pub gop_size: ::core::ffi::c_int,
    pub use_alt_ref: ::core::ffi::c_int,
}
pub type vpx_rc_encodeframe_info_t = vpx_rc_encodeframe_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_encodeframe_result {
    pub bit_count: i64,
    pub actual_encoding_qindex: ::core::ffi::c_int,
}
pub type vpx_rc_encodeframe_result_t = vpx_rc_encodeframe_result;
pub const vpx_rc_status_VPX_RC_OK: vpx_rc_status = 0;
pub const vpx_rc_status_VPX_RC_ERROR: vpx_rc_status = 1;
pub type vpx_rc_status = ::core::ffi::c_uint;
pub use self::vpx_rc_status as vpx_rc_status_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_frame_stats {
    pub frame: f64,
    pub weight: f64,
    pub intra_error: f64,
    pub coded_error: f64,
    pub sr_coded_error: f64,
    pub frame_noise_energy: f64,
    pub pcnt_inter: f64,
    pub pcnt_motion: f64,
    pub pcnt_second_ref: f64,
    pub pcnt_neutral: f64,
    pub pcnt_intra_low: f64,
    pub pcnt_intra_high: f64,
    pub intra_skip_pct: f64,
    pub intra_smooth_pct: f64,
    pub inactive_zone_rows: f64,
    pub inactive_zone_cols: f64,
    pub MVr: f64,
    pub mvr_abs: f64,
    pub MVc: f64,
    pub mvc_abs: f64,
    pub MVrv: f64,
    pub MVcv: f64,
    pub mv_in_out_count: f64,
    pub duration: f64,
    pub count: f64,
    pub new_mv_count: f64,
}
pub type vpx_rc_frame_stats_t = vpx_rc_frame_stats;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_firstpass_stats {
    pub frame_stats: *mut vpx_rc_frame_stats_t,
    pub num_frames: ::core::ffi::c_int,
}
pub type vpx_rc_firstpass_stats_t = vpx_rc_firstpass_stats;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_config {
    pub frame_width: ::core::ffi::c_int,
    pub frame_height: ::core::ffi::c_int,
    pub show_frame_count: ::core::ffi::c_int,
    pub max_gf_interval: ::core::ffi::c_int,
    pub min_gf_interval: ::core::ffi::c_int,
    pub target_bitrate_kbps: ::core::ffi::c_int,
    pub frame_rate_num: ::core::ffi::c_int,
    pub frame_rate_den: ::core::ffi::c_int,
    pub rc_mode: vpx_ext_rc_mode_t,
    pub overshoot_percent: ::core::ffi::c_int,
    pub undershoot_percent: ::core::ffi::c_int,
    pub min_base_q_index: ::core::ffi::c_int,
    pub max_base_q_index: ::core::ffi::c_int,
    pub base_qp: ::core::ffi::c_int,
}
pub type vpx_rc_config_t = vpx_rc_config;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_ref_frame {
    pub index: [::core::ffi::c_int; 4usize],
    pub name: [vpx_rc_ref_name_t; 4usize],
}
pub type vpx_rc_ref_frame_t = vpx_rc_ref_frame;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_gop_decision {
    pub gop_coding_frames: ::core::ffi::c_int,
    pub use_alt_ref: ::core::ffi::c_int,
    pub use_key_frame: ::core::ffi::c_int,
    pub update_type: [vpx_rc_frame_update_type_t; 252usize],
    pub update_ref_index: [::core::ffi::c_int; 252usize],
    pub ref_frame_list: [vpx_rc_ref_frame_t; 252usize],
}
pub type vpx_rc_gop_decision_t = vpx_rc_gop_decision;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_key_frame_decision {
    pub key_frame_show_index: ::core::ffi::c_int,
    pub key_frame_group_size: ::core::ffi::c_int,
}
pub type vpx_rc_key_frame_decision_t = vpx_rc_key_frame_decision;
pub type vpx_rc_create_model_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        priv_: *mut ::core::ffi::c_void,
        ratectrl_config: *const vpx_rc_config_t,
        rate_ctrl_model_ptr: *mut vpx_rc_model_t,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_send_firstpass_stats_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        first_pass_stats: *const vpx_rc_firstpass_stats_t,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_send_tpl_gop_stats_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        tpl_gop_stats: *const VpxTplGopStats,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_get_encodeframe_decision_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        frame_gop_index: ::core::ffi::c_int,
        frame_decision: *mut vpx_rc_encodeframe_decision_t,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_update_encodeframe_result_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        encode_frame_result: *const vpx_rc_encodeframe_result_t,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_get_key_frame_decision_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        key_frame_decision: *mut vpx_rc_key_frame_decision_t,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_get_gop_decision_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        gop_decision: *mut vpx_rc_gop_decision_t,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_get_frame_rdmult_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(
        rate_ctrl_model: vpx_rc_model_t,
        frame_info: *const vpx_rc_encodeframe_info_t,
        rdmult: *mut ::core::ffi::c_int,
    ) -> vpx_rc_status_t,
>;
pub type vpx_rc_delete_model_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(rate_ctrl_model: vpx_rc_model_t) -> vpx_rc_status_t,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rc_funcs {
    pub rc_type: vpx_rc_type_t,
    pub create_model: vpx_rc_create_model_cb_fn_t,
    pub send_firstpass_stats: vpx_rc_send_firstpass_stats_cb_fn_t,
    pub send_tpl_gop_stats: vpx_rc_send_tpl_gop_stats_cb_fn_t,
    pub get_encodeframe_decision: vpx_rc_get_encodeframe_decision_cb_fn_t,
    pub update_encodeframe_result: vpx_rc_update_encodeframe_result_cb_fn_t,
    pub get_key_frame_decision: vpx_rc_get_key_frame_decision_cb_fn_t,
    pub get_gop_decision: vpx_rc_get_gop_decision_cb_fn_t,
    pub get_frame_rdmult: vpx_rc_get_frame_rdmult_cb_fn_t,
    pub delete_model: vpx_rc_delete_model_cb_fn_t,
    pub rate_ctrl_log_path: *const ::core::ffi::c_char,
    pub priv_: *mut ::core::ffi::c_void,
}
pub type vpx_rc_funcs_t = vpx_rc_funcs;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_fixed_buf {
    pub buf: *mut ::core::ffi::c_void,
    pub sz: usize,
}
pub type vpx_fixed_buf_t = vpx_fixed_buf;
pub type vpx_codec_pts_t = i64;
pub type vpx_codec_frame_flags_t = u32;
pub type vpx_codec_er_flags_t = u32;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_CX_FRAME_PKT: vpx_codec_cx_pkt_kind = 0;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_STATS_PKT: vpx_codec_cx_pkt_kind = 1;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_FPMB_STATS_PKT: vpx_codec_cx_pkt_kind = 2;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_PSNR_PKT: vpx_codec_cx_pkt_kind = 3;
pub const vpx_codec_cx_pkt_kind_VPX_CODEC_CUSTOM_PKT: vpx_codec_cx_pkt_kind = 256;
pub type vpx_codec_cx_pkt_kind = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct vpx_codec_cx_pkt {
    pub kind: vpx_codec_cx_pkt_kind,
    pub data: vpx_codec_cx_pkt__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union vpx_codec_cx_pkt__bindgen_ty_1 {
    pub frame: vpx_codec_cx_pkt__bindgen_ty_1__bindgen_ty_1,
    pub twopass_stats: vpx_fixed_buf_t,
    pub firstpass_mb_stats: vpx_fixed_buf_t,
    pub psnr: vpx_codec_cx_pkt__bindgen_ty_1_vpx_psnr_pkt,
    pub raw: vpx_fixed_buf_t,
    pub pad: [::core::ffi::c_char; 124usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_cx_pkt__bindgen_ty_1__bindgen_ty_1 {
    pub buf: *mut ::core::ffi::c_void,
    pub sz: usize,
    pub pts: vpx_codec_pts_t,
    pub duration: ::core::ffi::c_ulong,
    pub flags: vpx_codec_frame_flags_t,
    pub partition_id: ::core::ffi::c_int,
    pub width: [::core::ffi::c_uint; 5usize],
    pub height: [::core::ffi::c_uint; 5usize],
    pub spatial_layer_encoded: [u8; 5usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_cx_pkt__bindgen_ty_1_vpx_psnr_pkt {
    pub samples: [::core::ffi::c_uint; 4usize],
    pub sse: [u64; 4usize],
    pub psnr: [f64; 4usize],
    pub spatial_layer_id: ::core::ffi::c_int,
}
pub type vpx_codec_cx_pkt_t = vpx_codec_cx_pkt;
pub type vpx_codec_enc_output_cx_pkt_cb_fn_t = ::core::option::Option<
    unsafe extern "C" fn(pkt: *mut vpx_codec_cx_pkt_t, user_data: *mut ::core::ffi::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_enc_output_cx_cb_pair {
    pub output_cx_pkt: vpx_codec_enc_output_cx_pkt_cb_fn_t,
    pub user_priv: *mut ::core::ffi::c_void,
}
pub type vpx_codec_priv_output_cx_pkt_cb_pair_t = vpx_codec_enc_output_cx_cb_pair;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_rational {
    pub num: ::core::ffi::c_int,
    pub den: ::core::ffi::c_int,
}
pub type vpx_rational_t = vpx_rational;
pub const vpx_enc_pass_VPX_RC_ONE_PASS: vpx_enc_pass = 0;
pub const vpx_enc_pass_VPX_RC_FIRST_PASS: vpx_enc_pass = 1;
pub const vpx_enc_pass_VPX_RC_LAST_PASS: vpx_enc_pass = 2;
pub type vpx_enc_pass = ::core::ffi::c_uint;
pub const vpx_rc_mode_VPX_VBR: vpx_rc_mode = 0;
pub const vpx_rc_mode_VPX_CBR: vpx_rc_mode = 1;
pub const vpx_rc_mode_VPX_CQ: vpx_rc_mode = 2;
pub const vpx_rc_mode_VPX_Q: vpx_rc_mode = 3;
pub type vpx_rc_mode = ::core::ffi::c_uint;
pub const vpx_kf_mode_VPX_KF_FIXED: vpx_kf_mode = 0;
pub const vpx_kf_mode_VPX_KF_AUTO: vpx_kf_mode = 1;
pub const vpx_kf_mode_VPX_KF_DISABLED: vpx_kf_mode = 0;
pub type vpx_kf_mode = ::core::ffi::c_uint;
pub type vpx_enc_frame_flags_t = ::core::ffi::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_enc_cfg {
    pub g_usage: ::core::ffi::c_uint,
    pub g_threads: ::core::ffi::c_uint,
    pub g_profile: ::core::ffi::c_uint,
    pub g_w: ::core::ffi::c_uint,
    pub g_h: ::core::ffi::c_uint,
    pub g_bit_depth: vpx_bit_depth_t,
    pub g_input_bit_depth: ::core::ffi::c_uint,
    pub g_timebase: vpx_rational,
    pub g_error_resilient: vpx_codec_er_flags_t,
    pub g_pass: vpx_enc_pass,
    pub g_lag_in_frames: ::core::ffi::c_uint,
    pub rc_dropframe_thresh: ::core::ffi::c_uint,
    pub rc_resize_allowed: ::core::ffi::c_uint,
    pub rc_scaled_width: ::core::ffi::c_uint,
    pub rc_scaled_height: ::core::ffi::c_uint,
    pub rc_resize_up_thresh: ::core::ffi::c_uint,
    pub rc_resize_down_thresh: ::core::ffi::c_uint,
    pub rc_end_usage: vpx_rc_mode,
    pub rc_twopass_stats_in: vpx_fixed_buf_t,
    pub rc_firstpass_mb_stats_in: vpx_fixed_buf_t,
    pub rc_target_bitrate: ::core::ffi::c_uint,
    pub rc_min_quantizer: ::core::ffi::c_uint,
    pub rc_max_quantizer: ::core::ffi::c_uint,
    pub rc_undershoot_pct: ::core::ffi::c_uint,
    pub rc_overshoot_pct: ::core::ffi::c_uint,
    pub rc_buf_sz: ::core::ffi::c_uint,
    pub rc_buf_initial_sz: ::core::ffi::c_uint,
    pub rc_buf_optimal_sz: ::core::ffi::c_uint,
    pub rc_2pass_vbr_bias_pct: ::core::ffi::c_uint,
    pub rc_2pass_vbr_minsection_pct: ::core::ffi::c_uint,
    pub rc_2pass_vbr_maxsection_pct: ::core::ffi::c_uint,
    pub rc_2pass_vbr_corpus_complexity: ::core::ffi::c_uint,
    pub kf_mode: vpx_kf_mode,
    pub kf_min_dist: ::core::ffi::c_uint,
    pub kf_max_dist: ::core::ffi::c_uint,
    pub ss_number_layers: ::core::ffi::c_uint,
    pub ss_enable_auto_alt_ref: [::core::ffi::c_int; 5usize],
    pub ss_target_bitrate: [::core::ffi::c_uint; 5usize],
    pub ts_number_layers: ::core::ffi::c_uint,
    pub ts_target_bitrate: [::core::ffi::c_uint; 5usize],
    pub ts_rate_decimator: [::core::ffi::c_uint; 5usize],
    pub ts_periodicity: ::core::ffi::c_uint,
    pub ts_layer_id: [::core::ffi::c_uint; 16usize],
    pub layer_target_bitrate: [::core::ffi::c_uint; 12usize],
    pub temporal_layering_mode: ::core::ffi::c_int,
    pub use_vizier_rc_params: ::core::ffi::c_int,
    pub active_wq_factor: vpx_rational_t,
    pub err_per_mb_factor: vpx_rational_t,
    pub sr_default_decay_limit: vpx_rational_t,
    pub sr_diff_factor: vpx_rational_t,
    pub kf_err_per_mb_factor: vpx_rational_t,
    pub kf_frame_min_boost_factor: vpx_rational_t,
    pub kf_frame_max_boost_first_factor: vpx_rational_t,
    pub kf_frame_max_boost_subs_factor: vpx_rational_t,
    pub kf_max_total_boost_factor: vpx_rational_t,
    pub gf_max_total_boost_factor: vpx_rational_t,
    pub gf_frame_max_boost_factor: vpx_rational_t,
    pub zm_factor: vpx_rational_t,
    pub rd_mult_inter_qp_fac: vpx_rational_t,
    pub rd_mult_arf_qp_fac: vpx_rational_t,
    pub rd_mult_key_qp_fac: vpx_rational_t,
}
pub type vpx_codec_enc_cfg_t = vpx_codec_enc_cfg;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_svc_parameters {
    pub max_quantizers: [::core::ffi::c_int; 12usize],
    pub min_quantizers: [::core::ffi::c_int; 12usize],
    pub scaling_factor_num: [::core::ffi::c_int; 12usize],
    pub scaling_factor_den: [::core::ffi::c_int; 12usize],
    pub speed_per_layer: [::core::ffi::c_int; 12usize],
    pub temporal_layering_mode: ::core::ffi::c_int,
    pub loopfilter_ctrl: [::core::ffi::c_int; 12usize],
}
pub type vpx_svc_extra_cfg_t = vpx_svc_parameters;
unsafe extern "C" {
    pub fn vpx_codec_enc_init_ver(
        ctx: *mut vpx_codec_ctx_t,
        iface: *const vpx_codec_iface,
        cfg: *const vpx_codec_enc_cfg_t,
        flags: vpx_codec_flags_t,
        ver: ::core::ffi::c_int,
    ) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_enc_config_default(
        iface: *const vpx_codec_iface,
        cfg: *mut vpx_codec_enc_cfg_t,
        usage: ::core::ffi::c_uint,
    ) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_enc_config_set(
        ctx: *mut vpx_codec_ctx_t,
        cfg: *const vpx_codec_enc_cfg_t,
    ) -> vpx_codec_err_t;
}
pub type vpx_enc_deadline_t = ::core::ffi::c_ulong;
unsafe extern "C" {
    pub fn vpx_codec_encode(
        ctx: *mut vpx_codec_ctx_t,
        img: *const vpx_image_t,
        pts: vpx_codec_pts_t,
        duration: ::core::ffi::c_ulong,
        flags: vpx_enc_frame_flags_t,
        deadline: vpx_enc_deadline_t,
    ) -> vpx_codec_err_t;
}
unsafe extern "C" {
    pub fn vpx_codec_get_cx_data(
        ctx: *mut vpx_codec_ctx_t,
        iter: *mut vpx_codec_iter_t,
    ) -> *const vpx_codec_cx_pkt_t;
}
pub const vpx_ref_frame_type_VP8_LAST_FRAME: vpx_ref_frame_type = 1;
pub const vpx_ref_frame_type_VP8_GOLD_FRAME: vpx_ref_frame_type = 2;
pub const vpx_ref_frame_type_VP8_ALTR_FRAME: vpx_ref_frame_type = 4;
pub type vpx_ref_frame_type = ::core::ffi::c_uint;
pub use self::vpx_ref_frame_type as vpx_ref_frame_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_ref_frame {
    pub frame_type: vpx_ref_frame_type_t,
    pub img: vpx_image_t,
}
pub type vpx_ref_frame_t = vpx_ref_frame;
unsafe extern "C" {
    pub fn vpx_codec_vp9_cx() -> *const vpx_codec_iface;
}
pub const vp8e_enc_control_id_VP8E_SET_ROI_MAP: vp8e_enc_control_id = 8;
pub const vp8e_enc_control_id_VP8E_SET_ACTIVEMAP: vp8e_enc_control_id = 9;
pub const vp8e_enc_control_id_VP8E_SET_SCALEMODE: vp8e_enc_control_id = 11;
pub const vp8e_enc_control_id_VP8E_SET_CPUUSED: vp8e_enc_control_id = 13;
pub const vp8e_enc_control_id_VP8E_SET_ENABLEAUTOALTREF: vp8e_enc_control_id = 14;
pub const vp8e_enc_control_id_VP8E_SET_NOISE_SENSITIVITY: vp8e_enc_control_id = 15;
pub const vp8e_enc_control_id_VP8E_SET_SHARPNESS: vp8e_enc_control_id = 16;
pub const vp8e_enc_control_id_VP8E_SET_STATIC_THRESHOLD: vp8e_enc_control_id = 17;
pub const vp8e_enc_control_id_VP8E_SET_TOKEN_PARTITIONS: vp8e_enc_control_id = 18;
pub const vp8e_enc_control_id_VP8E_GET_LAST_QUANTIZER: vp8e_enc_control_id = 19;
pub const vp8e_enc_control_id_VP8E_GET_LAST_QUANTIZER_64: vp8e_enc_control_id = 20;
pub const vp8e_enc_control_id_VP8E_SET_ARNR_MAXFRAMES: vp8e_enc_control_id = 21;
pub const vp8e_enc_control_id_VP8E_SET_ARNR_STRENGTH: vp8e_enc_control_id = 22;
pub const vp8e_enc_control_id_VP8E_SET_ARNR_TYPE: vp8e_enc_control_id = 23;
pub const vp8e_enc_control_id_VP8E_SET_TUNING: vp8e_enc_control_id = 24;
pub const vp8e_enc_control_id_VP8E_SET_CQ_LEVEL: vp8e_enc_control_id = 25;
pub const vp8e_enc_control_id_VP8E_SET_MAX_INTRA_BITRATE_PCT: vp8e_enc_control_id = 26;
pub const vp8e_enc_control_id_VP8E_SET_FRAME_FLAGS: vp8e_enc_control_id = 27;
pub const vp8e_enc_control_id_VP9E_SET_MAX_INTER_BITRATE_PCT: vp8e_enc_control_id = 28;
pub const vp8e_enc_control_id_VP9E_SET_GF_CBR_BOOST_PCT: vp8e_enc_control_id = 29;
pub const vp8e_enc_control_id_VP8E_SET_TEMPORAL_LAYER_ID: vp8e_enc_control_id = 30;
pub const vp8e_enc_control_id_VP8E_SET_SCREEN_CONTENT_MODE: vp8e_enc_control_id = 31;
pub const vp8e_enc_control_id_VP9E_SET_LOSSLESS: vp8e_enc_control_id = 32;
pub const vp8e_enc_control_id_VP9E_SET_TILE_COLUMNS: vp8e_enc_control_id = 33;
pub const vp8e_enc_control_id_VP9E_SET_TILE_ROWS: vp8e_enc_control_id = 34;
pub const vp8e_enc_control_id_VP9E_SET_FRAME_PARALLEL_DECODING: vp8e_enc_control_id = 35;
pub const vp8e_enc_control_id_VP9E_SET_AQ_MODE: vp8e_enc_control_id = 36;
pub const vp8e_enc_control_id_VP9E_SET_FRAME_PERIODIC_BOOST: vp8e_enc_control_id = 37;
pub const vp8e_enc_control_id_VP9E_SET_NOISE_SENSITIVITY: vp8e_enc_control_id = 38;
pub const vp8e_enc_control_id_VP9E_SET_SVC: vp8e_enc_control_id = 39;
pub const vp8e_enc_control_id_VP9E_SET_ROI_MAP: vp8e_enc_control_id = 40;
pub const vp8e_enc_control_id_VP9E_SET_SVC_PARAMETERS: vp8e_enc_control_id = 41;
pub const vp8e_enc_control_id_VP9E_SET_SVC_LAYER_ID: vp8e_enc_control_id = 42;
pub const vp8e_enc_control_id_VP9E_SET_TUNE_CONTENT: vp8e_enc_control_id = 43;
pub const vp8e_enc_control_id_VP9E_GET_SVC_LAYER_ID: vp8e_enc_control_id = 44;
pub const vp8e_enc_control_id_VP9E_REGISTER_CX_CALLBACK: vp8e_enc_control_id = 45;
pub const vp8e_enc_control_id_VP9E_SET_COLOR_SPACE: vp8e_enc_control_id = 46;
pub const vp8e_enc_control_id_VP9E_SET_MIN_GF_INTERVAL: vp8e_enc_control_id = 48;
pub const vp8e_enc_control_id_VP9E_SET_MAX_GF_INTERVAL: vp8e_enc_control_id = 49;
pub const vp8e_enc_control_id_VP9E_GET_ACTIVEMAP: vp8e_enc_control_id = 50;
pub const vp8e_enc_control_id_VP9E_SET_COLOR_RANGE: vp8e_enc_control_id = 51;
pub const vp8e_enc_control_id_VP9E_SET_SVC_REF_FRAME_CONFIG: vp8e_enc_control_id = 52;
pub const vp8e_enc_control_id_VP9E_SET_RENDER_SIZE: vp8e_enc_control_id = 53;
pub const vp8e_enc_control_id_VP9E_SET_TARGET_LEVEL: vp8e_enc_control_id = 54;
pub const vp8e_enc_control_id_VP9E_SET_ROW_MT: vp8e_enc_control_id = 55;
pub const vp8e_enc_control_id_VP9E_GET_LEVEL: vp8e_enc_control_id = 56;
pub const vp8e_enc_control_id_VP9E_SET_ALT_REF_AQ: vp8e_enc_control_id = 57;
pub const vp8e_enc_control_id_VP8E_SET_GF_CBR_BOOST_PCT: vp8e_enc_control_id = 58;
pub const vp8e_enc_control_id_VP9E_ENABLE_MOTION_VECTOR_UNIT_TEST: vp8e_enc_control_id = 59;
pub const vp8e_enc_control_id_VP9E_SET_SVC_INTER_LAYER_PRED: vp8e_enc_control_id = 60;
pub const vp8e_enc_control_id_VP9E_SET_SVC_FRAME_DROP_LAYER: vp8e_enc_control_id = 61;
pub const vp8e_enc_control_id_VP9E_GET_SVC_REF_FRAME_CONFIG: vp8e_enc_control_id = 62;
pub const vp8e_enc_control_id_VP9E_SET_SVC_GF_TEMPORAL_REF: vp8e_enc_control_id = 63;
pub const vp8e_enc_control_id_VP9E_SET_SVC_SPATIAL_LAYER_SYNC: vp8e_enc_control_id = 64;
pub const vp8e_enc_control_id_VP9E_SET_TPL: vp8e_enc_control_id = 65;
pub const vp8e_enc_control_id_VP9E_SET_POSTENCODE_DROP: vp8e_enc_control_id = 66;
pub const vp8e_enc_control_id_VP9E_SET_DELTA_Q_UV: vp8e_enc_control_id = 67;
pub const vp8e_enc_control_id_VP9E_SET_DISABLE_OVERSHOOT_MAXQ_CBR: vp8e_enc_control_id = 68;
pub const vp8e_enc_control_id_VP9E_SET_DISABLE_LOOPFILTER: vp8e_enc_control_id = 69;
pub const vp8e_enc_control_id_VP9E_SET_EXTERNAL_RATE_CONTROL: vp8e_enc_control_id = 70;
pub const vp8e_enc_control_id_VP9E_SET_RTC_EXTERNAL_RATECTRL: vp8e_enc_control_id = 71;
pub const vp8e_enc_control_id_VP9E_GET_LOOPFILTER_LEVEL: vp8e_enc_control_id = 72;
pub const vp8e_enc_control_id_VP9E_GET_LAST_QUANTIZER_SVC_LAYERS: vp8e_enc_control_id = 73;
pub const vp8e_enc_control_id_VP8E_SET_RTC_EXTERNAL_RATECTRL: vp8e_enc_control_id = 74;
pub const vp8e_enc_control_id_VP9E_SET_QUANTIZER_ONE_PASS: vp8e_enc_control_id = 75;
pub const vp8e_enc_control_id_VP9E_SET_KEY_FRAME_FILTERING: vp8e_enc_control_id = 76;
pub const vp8e_enc_control_id_VP9E_SET_VALIDATE_HBD_INPUT: vp8e_enc_control_id = 77;
pub type vp8e_enc_control_id = ::core::ffi::c_uint;
pub const vpx_scaling_mode_1d_VP8E_NORMAL: vpx_scaling_mode_1d = 0;
pub const vpx_scaling_mode_1d_VP8E_FOURFIVE: vpx_scaling_mode_1d = 1;
pub const vpx_scaling_mode_1d_VP8E_THREEFIVE: vpx_scaling_mode_1d = 2;
pub const vpx_scaling_mode_1d_VP8E_ONETWO: vpx_scaling_mode_1d = 3;
pub type vpx_scaling_mode_1d = ::core::ffi::c_uint;
pub use self::vpx_scaling_mode_1d as VPX_SCALING_MODE;
pub const vp9e_temporal_layering_mode_VP9E_TEMPORAL_LAYERING_MODE_NOLAYERING:
    vp9e_temporal_layering_mode = 0;
pub const vp9e_temporal_layering_mode_VP9E_TEMPORAL_LAYERING_MODE_BYPASS:
    vp9e_temporal_layering_mode = 1;
pub const vp9e_temporal_layering_mode_VP9E_TEMPORAL_LAYERING_MODE_0101:
    vp9e_temporal_layering_mode = 2;
pub const vp9e_temporal_layering_mode_VP9E_TEMPORAL_LAYERING_MODE_0212:
    vp9e_temporal_layering_mode = 3;
pub type vp9e_temporal_layering_mode = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_roi_map {
    pub enabled: u8,
    pub roi_map: *mut ::core::ffi::c_uchar,
    pub rows: ::core::ffi::c_uint,
    pub cols: ::core::ffi::c_uint,
    pub delta_q: [::core::ffi::c_int; 8usize],
    pub delta_lf: [::core::ffi::c_int; 8usize],
    pub skip: [::core::ffi::c_int; 8usize],
    pub ref_frame: [::core::ffi::c_int; 8usize],
    pub static_threshold: [::core::ffi::c_uint; 4usize],
}
pub type vpx_roi_map_t = vpx_roi_map;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_active_map {
    pub active_map: *mut ::core::ffi::c_uchar,
    pub rows: ::core::ffi::c_uint,
    pub cols: ::core::ffi::c_uint,
}
pub type vpx_active_map_t = vpx_active_map;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_scaling_mode {
    pub h_scaling_mode: VPX_SCALING_MODE,
    pub v_scaling_mode: VPX_SCALING_MODE,
}
pub type vpx_scaling_mode_t = vpx_scaling_mode;
pub const vp8e_token_partitions_VP8_ONE_TOKENPARTITION: vp8e_token_partitions = 0;
pub const vp8e_token_partitions_VP8_TWO_TOKENPARTITION: vp8e_token_partitions = 1;
pub const vp8e_token_partitions_VP8_FOUR_TOKENPARTITION: vp8e_token_partitions = 2;
pub const vp8e_token_partitions_VP8_EIGHT_TOKENPARTITION: vp8e_token_partitions = 3;
pub type vp8e_token_partitions = ::core::ffi::c_uint;
pub const vp9e_tune_content_VP9E_CONTENT_DEFAULT: vp9e_tune_content = 0;
pub const vp9e_tune_content_VP9E_CONTENT_SCREEN: vp9e_tune_content = 1;
pub const vp9e_tune_content_VP9E_CONTENT_FILM: vp9e_tune_content = 2;
pub const vp9e_tune_content_VP9E_CONTENT_INVALID: vp9e_tune_content = 3;
pub type vp9e_tune_content = ::core::ffi::c_uint;
pub const vp8e_tuning_VP8_TUNE_PSNR: vp8e_tuning = 0;
pub const vp8e_tuning_VP8_TUNE_SSIM: vp8e_tuning = 1;
pub type vp8e_tuning = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_svc_layer_id {
    pub spatial_layer_id: ::core::ffi::c_int,
    pub temporal_layer_id: ::core::ffi::c_int,
    pub temporal_layer_id_per_spatial: [::core::ffi::c_int; 5usize],
}
pub type vpx_svc_layer_id_t = vpx_svc_layer_id;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_svc_ref_frame_config {
    pub lst_fb_idx: [::core::ffi::c_int; 5usize],
    pub gld_fb_idx: [::core::ffi::c_int; 5usize],
    pub alt_fb_idx: [::core::ffi::c_int; 5usize],
    pub update_buffer_slot: [::core::ffi::c_int; 5usize],
    pub update_last: [::core::ffi::c_int; 5usize],
    pub update_golden: [::core::ffi::c_int; 5usize],
    pub update_alt_ref: [::core::ffi::c_int; 5usize],
    pub reference_last: [::core::ffi::c_int; 5usize],
    pub reference_golden: [::core::ffi::c_int; 5usize],
    pub reference_alt_ref: [::core::ffi::c_int; 5usize],
    pub duration: [i64; 5usize],
}
pub type vpx_svc_ref_frame_config_t = vpx_svc_ref_frame_config;
pub const SVC_LAYER_DROP_MODE_CONSTRAINED_LAYER_DROP: SVC_LAYER_DROP_MODE = 0;
pub const SVC_LAYER_DROP_MODE_LAYER_DROP: SVC_LAYER_DROP_MODE = 1;
pub const SVC_LAYER_DROP_MODE_FULL_SUPERFRAME_DROP: SVC_LAYER_DROP_MODE = 2;
pub const SVC_LAYER_DROP_MODE_CONSTRAINED_FROM_ABOVE_DROP: SVC_LAYER_DROP_MODE = 3;
pub type SVC_LAYER_DROP_MODE = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_svc_frame_drop {
    pub framedrop_thresh: [::core::ffi::c_int; 5usize],
    pub framedrop_mode: SVC_LAYER_DROP_MODE,
    pub max_consec_drop: ::core::ffi::c_int,
}
pub type vpx_svc_frame_drop_t = vpx_svc_frame_drop;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_svc_spatial_layer_sync {
    pub spatial_layer_sync: [::core::ffi::c_int; 5usize],
    pub base_layer_intra_only: ::core::ffi::c_int,
}
pub type vpx_svc_spatial_layer_sync_t = vpx_svc_spatial_layer_sync;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpx_codec_dec_cfg {
    pub _address: u8,
}
